import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: '#f6f7fb',
    },
    headerGradient: {
        paddingTop: 50,
        paddingBottom: 15,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButton: {
        marginRight: 15,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'white',
    },
    searchContainer: {
        backgroundColor: 'white',
        margin: 15,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 15,
        paddingVertical: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#4B5563',
    },
    clearButton: {
        padding: 5,
    },
    filterContainer: {
        marginBottom: 10,
    },
    filterContent: {
        paddingHorizontal: 15,
        paddingVertical: 5,
    },
    filterButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        paddingHorizontal: 15,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
    },
    filterButtonActive: {
        backgroundColor: '#4F6CE1',
    },
    filterButtonText: {
        fontSize: 14,
        color: '#4B5563',
        marginLeft: 5,
    },
    filterButtonTextActive: {
        color: 'white',
    },
    listContainer: {
        padding: 15,
    },
    borrowCard: {
        backgroundColor: 'white',
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 3,
        marginBottom: 15,
        overflow: 'hidden',
    },
    borrowHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F7FAFC',
        padding: 15,
    },
    bookTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#2D3748',
        flex: 1,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 15,
        paddingHorizontal: 10,
        paddingVertical: 5,
        marginLeft: 10,
    },
    statusText: {
        color: 'white',
        fontSize: 12,
        fontWeight: '600',
    },
    borrowContent: {
        flexDirection: 'row',
        padding: 15,
    },
    coverThumbnail: {
        width: 80,
        height: 120,
        borderRadius: 5,
        backgroundColor: '#E2E8F0',
    },
    borrowInfo: {
        flex: 1,
        marginLeft: 15,
    },
    authorName: {
        fontSize: 14,
        color: '#4A5568',
        fontWeight: '500',
        marginBottom: 8,
    },
    userInfoBox: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    userInfoText: {
        fontSize: 14,
        color: '#4B5563',
        marginLeft: 8,
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    dateText: {
        fontSize: 13,
        color: '#718096',
        marginLeft: 8,
    },
    notesContainer: {
        marginTop: 10,
        padding: 10,
        backgroundColor: '#F7FAFC',
        borderRadius: 8,
    },
    notesLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#4A5568',
        marginBottom: 5,
    },
    notesText: {
        fontSize: 13,
        color: '#718096',
        fontStyle: 'italic',
    },
    manageButton: {
        borderRadius: 0,
        overflow: 'hidden',
    },
    manageButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 15,
    },
    manageButtonText: {
        color: 'white',
        fontSize: 15,
        fontWeight: '600',
        marginLeft: 8,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
        color: '#4A5568',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#4A5568',
        marginTop: 20,
    },
    emptySubText: {
        fontSize: 14,
        color: '#718096',
        textAlign: 'center',
        marginTop: 10,
        marginBottom: 20,
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalView: {
        backgroundColor: 'white',
        borderRadius: 15,
        width: '90%',
        maxHeight: '80%',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        overflow: 'hidden',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F7FAFC',
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2D3748',
    },
    closeButton: {
        padding: 5,
    },
    modalContent: {
        padding: 20,
    },
    modalBookTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#2D3748',
        marginBottom: 5,
    },
    modalUserInfo: {
        fontSize: 14,
        color: '#4A5568',
        marginBottom: 15,
    },
    modalQuantityContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FAFC',
        padding: 10,
        borderRadius: 8,
        marginBottom: 15,
    },
    modalQuantityText: {
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 10,
    },
    notesInput: {
        backgroundColor: '#F7FAFC',
        borderRadius: 8,
        padding: 12,
        height: 100,
        textAlignVertical: 'top',
        color: '#4A5568',
        fontSize: 14,
        marginBottom: 20,
    },
    modalActions: {
        gap: 10,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        borderRadius: 8,
    },
    actionButtonText: {
        color: 'white',
        fontSize: 15,
        fontWeight: '600',
        marginLeft: 8,
    },
    approveButton: {
        backgroundColor: '#10B981',
    },
    rejectButton: {
        backgroundColor: '#EF4444',
    },
    confirmButton: {
        backgroundColor: '#3B82F6',
    },
    returnButton: {
        backgroundColor: '#DD6B20',
    },
    cancelButton: {
        backgroundColor: '#6B7280',
    },
    disabledButton: {
        opacity: 0.6,
    },
    stockInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    stockText: {
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
});
